import { create } from 'zustand';
import { subscribeWithSelector } from 'zustand/middleware';
import { AppState, NavigationState, AppSettings, GPSPosition } from '../types';
import {
  FeatureCollection,
  LineString,
  Point,
  GeoJsonProperties,
} from 'geojson';
import { RoutePoint } from '../components/RouteBuilder/types';
import { getLocalVersion } from '../utils/versionCheck';

export type AppMode = 'roadbook' | 'routePlanning' | 'routesList' | 'settings';

export interface RoadbookIndexEntry {
  // 1-based index, matches PDF marker numbering (#1, #2, ...)
  index: number;
  // distance from start in meters
  distance: number;
  lat: number;
  lng: number;
}

interface AppStore extends AppState {
  // State properties
  turns: any[];
  navigation: NavigationState;
  settings: AppSettings;
  odometer: number;
  isMoving: boolean;
  autoFollow: boolean;
  route: FeatureCollection<LineString, GeoJsonProperties> | undefined;

  // Orientation state
  isLandscape: boolean;

  // Version check state
  versionInfo: {
    local: string | null;
    localBuildTime: string | null;
  };

  // Roadbook entries were previously stored here for the legacy (native/SSE) roadbook UI.
  // The app now renders the roadbook as PDF, so this state is intentionally removed.

  // Current route information
  currentRouteId: string | null;
  currentRouteName: string | null;
  currentRouteKey: string | null;
  routeProfile: string; // Routing profile used
  waypoints:
    | {
        lat: number;
        lon: number;
      }[]
    | undefined;
  // Route builder state
  isRouteBuilderOpen: boolean;
  routeBuilderPoints: RoutePoint[];
  routeBuilderData: FeatureCollection<LineString, GeoJsonProperties> | null;
  routeBuilderTurnPoints: FeatureCollection<Point, GeoJsonProperties> | null;
  routeBuilderLoadingData: FeatureCollection<
    LineString,
    GeoJsonProperties
  > | null;
  routeBuilderIsLoading: boolean;
  routeBuilderError: string | null;
  routeBuilderSelectedName: string;
  routeBuilderProfile: string;
  routeBuilderAutoGeneratedName: string;
  routeBuilderIsNameManuallySet: boolean;
  routeBuilderMapView: {
    latitude: number;
    longitude: number;
    zoom: number;
  } | null;
  // GPX underlay (imported GPX displayed in background)
  routeBuilderGpxUnderlay: FeatureCollection<
    LineString,
    GeoJsonProperties
  > | null;

  // UI state
  isHeaderExpanded: boolean;

  // PDF roadbook index (distance + lat/lng + marker index)
  roadbookIndex: RoadbookIndexEntry[];
  currentRoadbookIndex: number | null;

  // Actions
  setNavigation: (navigation: NavigationState) => void;
  setGpsPosition: (gpsPosition: GPSPosition | undefined) => void;
  requestInitialLocation: () => Promise<void>;
  setOdometer: (odometer: number) => void;
  setIsMoving: (isMoving: boolean) => void;
  setAutoFollow: (autoFollow: boolean) => void;
  resetOdometer: () => void;
  incrementOdometer: (distance: number) => void;
  loadRoute: (
    routeData: FeatureCollection<LineString>,

    routeId?: string,
    waypoints?: { lat: number; lon: number }[],
    profile?: string,
    routeName?: string
  ) => void;
  setCurrentRouteId: (routeId: string | null) => void;
  setCurrentRouteName: (routeName: string | null) => void;
  setCurrentRouteKey: (routeKey: string | null) => void;
  setRouteProfile: (profile: string) => void;
  setSettings: (settings: AppSettings) => void;

  // Route builder actions
  openRouteBuilder: () => void;
  closeRouteBuilder: () => void;
  setRouteBuilderPoints: (points: RoutePoint[]) => void;
  setRouteBuilderData: (
    data: FeatureCollection<LineString, GeoJsonProperties> | null
  ) => void;
  setRouteBuilderTurnPoints: (
    points: FeatureCollection<Point, GeoJsonProperties> | null
  ) => void;
  setRouteBuilderLoadingData: (
    data: FeatureCollection<LineString, GeoJsonProperties> | null
  ) => void;
  setRouteBuilderIsLoading: (isLoading: boolean) => void;
  setRouteBuilderError: (error: string | null) => void;
  setRouteBuilderSelectedName: (name: string) => void;
  setRouteBuilderProfile: (profile: string) => void;
  setRouteBuilderAutoGeneratedName: (name: string) => void;
  setRouteBuilderIsNameManuallySet: (isSet: boolean) => void;
  setRouteBuilderMapView: (
    view: { latitude: number; longitude: number; zoom: number } | null
  ) => void;
  setRouteBuilderGpxUnderlay: (
    data: FeatureCollection<LineString, GeoJsonProperties> | null
  ) => void;
  resetRouteBuilder: () => void;

  // UI actions
  setIsHeaderExpanded: (isHeaderExpanded: boolean) => void;
  toggleHeaderExpanded: () => void;
  setIsLandscape: (isLandscape: boolean) => void;

  // Roadbook index actions
  setRoadbookIndex: (entries: RoadbookIndexEntry[]) => void;
  setCurrentRoadbookIndex: (index: number | null) => void;

  // Roadbook loading actions
  // (removed)
}

export const useAppStore = create<AppStore>()(
  subscribeWithSelector(set => ({
    // Initial state
    turns: [],
    navigation: {
      distanceToNextTurn: 0,
      isOnRoute: false,
      routeProgress: 0,
    },
    settings: {
      keepScreenOn: true,
      odometerDecreaseKey: 'ArrowLeft',
      odometerIncreaseKey: 'ArrowRight',
      roadbookScrollUpKey: 'ArrowUp',
      roadbookScrollDownKey: 'ArrowDown',
      autoFollowToggleKey: 'Space',
      roadbookScrollMode: 'continuous',
      roadbookScrollSpeed: 30,
      closeDistanceThreshold: 200,
    },
    odometer: 0,
    isMoving: false,
    autoFollow: true,
    route: undefined,
    waypoints: undefined,

    // Current route information
    currentRouteId: null,
    currentRouteName: null,
    currentRouteKey: null,
    routeProfile: 'Car-FastEco', // Default routing profile

    // Route builder state
    isRouteBuilderOpen: false,
    routeBuilderPoints: [],
    routeBuilderData: null,
    routeBuilderTurnPoints: null,
    routeBuilderLoadingData: null,
    routeBuilderIsLoading: false,
    routeBuilderError: null,
    routeBuilderSelectedName: '',
    routeBuilderProfile: 'Car-FastEco',
    routeBuilderAutoGeneratedName: '',
    routeBuilderIsNameManuallySet: false,
    routeBuilderMapView: null,
    routeBuilderGpxUnderlay: null,

    // UI state
    isHeaderExpanded: false,
    isLandscape: false,

    // PDF roadbook index
    roadbookIndex: [],
    currentRoadbookIndex: null,

    // Version check state
    versionInfo: (() => {
      const localVersionData = getLocalVersion();
      return {
        local: localVersionData?.appVersion || null,
        localBuildTime: localVersionData?.buildVersion || null,
      };
    })(),

    // Actions
    setNavigation: (navigation: NavigationState) => set({ navigation }),

    setGpsPosition: (gpsPosition: GPSPosition | undefined) =>
      set(state => ({
        navigation: { ...state.navigation, currentPosition: gpsPosition },
      })),

    setOdometer: (odometer: number) => set({ odometer }),

    setIsMoving: (isMoving: boolean) => set({ isMoving }),

    setAutoFollow: (autoFollow: boolean) => set({ autoFollow }),

    resetOdometer: () => set({ odometer: 0 }),

    incrementOdometer: (distance: number) =>
      set(state => ({ odometer: state.odometer + distance })),

    loadRoute: (
      routeData: FeatureCollection<LineString>,
      routeId?: string,
      waypoints?: { lat: number; lon: number }[],
      profile?: string,
      routeName?: string
    ) => {
      set({
        route: routeData,

        waypoints: waypoints,
        currentRouteId: routeId || null,
        currentRouteName: routeName || null,
        currentRouteKey: JSON.stringify(waypoints),
        routeProfile: profile || 'enduro', // Store routing profile
        odometer: 0, // Reset odometer for new route
        roadbookIndex: [],
        currentRoadbookIndex: null,
      });
    },

    setCurrentRouteId: (routeId: string | null) =>
      set({ currentRouteId: routeId }),

    setCurrentRouteName: (routeName: string | null) =>
      set({ currentRouteName: routeName }),

    setCurrentRouteKey: (routeKey: string | null) =>
      set({ currentRouteKey: routeKey }),

    setRouteProfile: (profile: string) => set({ routeProfile: profile }),

    setSettings: (settings: AppSettings) => {
      set({ settings: { ...settings } }); // Ensure new object reference
    },

    // Route builder actions
    openRouteBuilder: () => set({ isRouteBuilderOpen: true }),

    closeRouteBuilder: () => set({ isRouteBuilderOpen: false }),

    setRouteBuilderPoints: (points: RoutePoint[]) =>
      set({ routeBuilderPoints: points }),

    setRouteBuilderData: (
      data: FeatureCollection<LineString, GeoJsonProperties> | null
    ) => set({ routeBuilderData: data }),

    setRouteBuilderTurnPoints: (
      points: FeatureCollection<Point, GeoJsonProperties> | null
    ) => set({ routeBuilderTurnPoints: points }),

    setRouteBuilderLoadingData: (
      data: FeatureCollection<LineString, GeoJsonProperties> | null
    ) => set({ routeBuilderLoadingData: data }),

    setRouteBuilderIsLoading: (isLoading: boolean) =>
      set({ routeBuilderIsLoading: isLoading }),

    setRouteBuilderError: (error: string | null) =>
      set({ routeBuilderError: error }),

    setRouteBuilderSelectedName: (name: string) =>
      set({ routeBuilderSelectedName: name }),

    setRouteBuilderProfile: (profile: string) =>
      set({ routeBuilderProfile: profile }),

    setRouteBuilderAutoGeneratedName: (name: string) =>
      set({ routeBuilderAutoGeneratedName: name }),

    setRouteBuilderIsNameManuallySet: (isSet: boolean) =>
      set({ routeBuilderIsNameManuallySet: isSet }),

    setRouteBuilderMapView: (
      view: { latitude: number; longitude: number; zoom: number } | null
    ) => set({ routeBuilderMapView: view }),

    setRouteBuilderGpxUnderlay: (
      data: FeatureCollection<LineString, GeoJsonProperties> | null
    ) => set({ routeBuilderGpxUnderlay: data }),

    resetRouteBuilder: () =>
      set({
        routeBuilderPoints: [],
        routeBuilderData: null,
        routeBuilderTurnPoints: null,
        routeBuilderLoadingData: null,
        routeBuilderIsLoading: false,
        routeBuilderError: null,
        routeBuilderSelectedName: '',
        routeBuilderAutoGeneratedName: '',
        routeBuilderIsNameManuallySet: false,
        routeBuilderGpxUnderlay: null,
      }),

    // UI actions
    setIsHeaderExpanded: (isHeaderExpanded: boolean) =>
      set({ isHeaderExpanded }),

    toggleHeaderExpanded: () =>
      set(state => ({ isHeaderExpanded: !state.isHeaderExpanded })),

    setIsLandscape: (isLandscape: boolean) => set({ isLandscape }),

    setRoadbookIndex: (entries: RoadbookIndexEntry[]) =>
      set({ roadbookIndex: entries }),
    setCurrentRoadbookIndex: (index: number | null) =>
      set({ currentRoadbookIndex: index }),

    // Initial location request
    requestInitialLocation: async () => {
      if (!navigator.geolocation) {
        return;
      }

      try {
        const position = await new Promise<GeolocationPosition>(
          (resolve, reject) => {
            navigator.geolocation.getCurrentPosition(resolve, reject, {
              timeout: 5000,
              maximumAge: 300000, // 5 minutes
            });
          }
        );

        const gpsPosition: GPSPosition = {
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          accuracy: position.coords.accuracy,
          altitude: position.coords.altitude || undefined,
          heading: position.coords.heading || undefined,
          speed: position.coords.speed || undefined,
          timestamp: position.timestamp,
        };

        set(state => ({
          navigation: { ...state.navigation, currentPosition: gpsPosition },
        }));
      } catch {
        // Initial positioning is best-effort; navigation can request it again.
      }
    },
  }))
);

// GPS Position hook
export const useGpsPosition = () =>
  useAppStore(state => state.navigation.currentPosition);

export const useRoadbookIndex = () => useAppStore(state => state.roadbookIndex);
