import { useCallback, useEffect } from 'react';
import type { MutableRefObject } from 'react';
import type { FeatureCollection, GeoJsonProperties, Point } from 'geojson';
import { useTranslation } from 'react-i18next';
import { fetchBrouterRoute } from '../../../services/localProjects';
import { generateRandomColor } from '../../../utils/colorUtils';
import { useRoutesStore } from '../../../stores/routesStore';
import type { RoutePoint } from '../types';
import {
  buildRoutePointsCoordsString,
  createStraightLineRoute,
  extractLocationName,
} from '../utils/routeBuilderUtils';
import {
  useRouteBuilderState,
  useRouteBuilderStoreActions,
} from './useRouteBuilderStore';

type TurnPointData = FeatureCollection<Point, GeoJsonProperties> | null;

interface UseRouteBuilderEffectsArgs {
  abortControllerRef: MutableRefObject<AbortController | null>;
  editRouteId?: string;
  hydratedEditRouteIdRef: MutableRefObject<string | null>;
  isRouteDraggingRef: MutableRefObject<boolean>;
  isRouteLoadingFromCacheRef: MutableRefObject<boolean>;
  pendingInitialEditFetchCoordsRef: MutableRefObject<string>;
  pendingInitialEditFetchProfileRef: MutableRefObject<string>;
  pendingInitialEditFetchRouteIdRef: MutableRefObject<string | null>;
  previousRoutePointsCoordsRef: MutableRefObject<string>;
  previousRoutingProfileRef: MutableRefObject<string>;
  setIsRouteTooLong: (isTooLong: boolean) => void;
  setRouteNameInput: (name: string) => void;
}

export const useRouteBuilderEffects = ({
  abortControllerRef,
  editRouteId,
  hydratedEditRouteIdRef,
  isRouteDraggingRef,
  isRouteLoadingFromCacheRef,
  pendingInitialEditFetchCoordsRef,
  pendingInitialEditFetchProfileRef,
  pendingInitialEditFetchRouteIdRef,
  previousRoutePointsCoordsRef,
  previousRoutingProfileRef,
  setIsRouteTooLong,
  setRouteNameInput,
}: UseRouteBuilderEffectsArgs) => {
  const { t } = useTranslation();
  const { error, isRouteNameManuallySet, routePoints, routingProfile } =
    useRouteBuilderState();
  const {
    setAutoGeneratedRouteName,
    setError,
    setGpxUnderlay,
    setIsRouteLoading,
    setIsRouteNameManuallySet,
    setLoadingRouteData,
    setRouteData,
    setRoutePoints,
    setRoutingProfile,
    setSelectedRouteName,
    setTurnPoints,
  } = useRouteBuilderStoreActions();
  const routes = useRoutesStore(state => state.routes);
  const loadRoutes = useRoutesStore(state => state.loadRoutes);

  useEffect(() => {
    if (!error) {
      return undefined;
    }

    const timer = setTimeout(() => {
      setError(null);
    }, 5000);

    return () => clearTimeout(timer);
  }, [error, setError]);

  useEffect(() => {
    abortControllerRef.current = new AbortController();

    return () => {
      abortControllerRef.current?.abort();
    };
  }, [abortControllerRef]);

  useEffect(() => {
    const loadData = async () => {
      await loadRoutes();
    };

    void loadData();
  }, [loadRoutes]);

  const fetchRouteForHandles = useCallback(
    async (points: RoutePoint[], profileOverride?: string) => {
      if (points.length < 2) {
        return;
      }

      const activeProfile = profileOverride || routingProfile;
      setIsRouteLoading(true);
      setError(null);
      setLoadingRouteData(createStraightLineRoute(points));

      try {
        abortControllerRef.current?.abort();
        abortControllerRef.current = new AbortController();

        const response = await fetchBrouterRoute(
          {
            points: points.map(point => ({ lat: point.lat, lon: point.lon })),
            routeId: editRouteId || undefined,
            profile: activeProfile,
          },
          abortControllerRef.current.signal
        );

        setRouteData(response.routeData);
        setTurnPoints(response.turnPoints as TurnPointData);
        setLoadingRouteData(null);

        setIsRouteTooLong(false);
      } catch (err: any) {
        if (err.name !== 'AbortError') {
          const errorMessage =
            err instanceof Error ? err.message : t('errors.routeLoadError');
          setError(errorMessage);
          console.error('Error fetching route:', err);

          if (
            errorMessage.includes('zu lang') ||
            errorMessage.includes('too long')
          ) {
            setIsRouteTooLong(true);
          }
        }

        setLoadingRouteData(null);
      } finally {
        setIsRouteLoading(false);
      }
    },
    [
      abortControllerRef,
      routingProfile,
      setError,
      setIsRouteLoading,
      setIsRouteTooLong,
      setLoadingRouteData,
      setRouteData,
      setTurnPoints,
      t,
    ]
  );

  useEffect(() => {
    if (!editRouteId) {
      const wasHydratedFromEditRoute = hydratedEditRouteIdRef.current !== null;

      if (wasHydratedFromEditRoute) {
        setError(null);
        setIsRouteLoading(false);
        setIsRouteTooLong(false);
        setGpxUnderlay(null);
        setRouteData(null);
        setTurnPoints(null);
        setLoadingRouteData(null);
        setRoutePoints([]);
        setSelectedRouteName('');
        setAutoGeneratedRouteName('');
        setIsRouteNameManuallySet(false);
        setRoutingProfile('enduro');
        setRouteNameInput('');
      }

      hydratedEditRouteIdRef.current = null;
      pendingInitialEditFetchRouteIdRef.current = null;
      pendingInitialEditFetchCoordsRef.current = '';
      pendingInitialEditFetchProfileRef.current = '';
      return;
    }

    const routeToEdit = routes.find(route => route.id === editRouteId);
    if (!routeToEdit) {
      return;
    }

    if (hydratedEditRouteIdRef.current === editRouteId) {
      return;
    }

    const hydratedProfile = routeToEdit.profile || 'enduro';
    const hydratedPoints = routeToEdit.waypoints.map((point, index) => ({
      id: `edit_point_${routeToEdit.id}_${index}`,
      lat: point.lat,
      lon: point.lon,
      color: generateRandomColor(),
      displayName: undefined,
    }));
    const hydratedCoordsString = buildRoutePointsCoordsString(hydratedPoints);

    hydratedEditRouteIdRef.current = editRouteId;
    pendingInitialEditFetchRouteIdRef.current = editRouteId;
    pendingInitialEditFetchCoordsRef.current = hydratedCoordsString;
    pendingInitialEditFetchProfileRef.current = hydratedProfile;
    previousRoutePointsCoordsRef.current = '';
    previousRoutingProfileRef.current = '';
    isRouteLoadingFromCacheRef.current = false;
    isRouteDraggingRef.current = false;

    setError(null);
    setIsRouteTooLong(false);
    setGpxUnderlay(null);
    setRouteData(null);
    setTurnPoints(null);
    setLoadingRouteData(null);
    setRoutingProfile(hydratedProfile);
    setRoutePoints(hydratedPoints);
    setSelectedRouteName(routeToEdit.name);
    setAutoGeneratedRouteName('');
    setIsRouteNameManuallySet(true);
    setRouteNameInput(routeToEdit.name);
  }, [
    editRouteId,
    hydratedEditRouteIdRef,
    isRouteDraggingRef,
    isRouteLoadingFromCacheRef,
    pendingInitialEditFetchCoordsRef,
    pendingInitialEditFetchProfileRef,
    pendingInitialEditFetchRouteIdRef,
    previousRoutePointsCoordsRef,
    previousRoutingProfileRef,
    routes,
    setAutoGeneratedRouteName,
    setError,
    setGpxUnderlay,
    setIsRouteNameManuallySet,
    setIsRouteTooLong,
    setLoadingRouteData,
    setRouteData,
    setRouteNameInput,
    setRoutePoints,
    setRoutingProfile,
    setSelectedRouteName,
    setTurnPoints,
  ]);

  useEffect(() => {
    const coordsString = buildRoutePointsCoordsString(routePoints);
    const shouldRunPendingInitialEditFetch =
      pendingInitialEditFetchRouteIdRef.current === editRouteId &&
      coordsString === pendingInitialEditFetchCoordsRef.current &&
      routingProfile === pendingInitialEditFetchProfileRef.current;

    const coordsChanged = coordsString !== previousRoutePointsCoordsRef.current;
    const profileChanged = routingProfile !== previousRoutingProfileRef.current;

    previousRoutePointsCoordsRef.current = coordsString;
    previousRoutingProfileRef.current = routingProfile;

    if (
      routePoints.length >= 2 &&
      !isRouteLoadingFromCacheRef.current &&
      !isRouteDraggingRef.current &&
      (coordsChanged || profileChanged || shouldRunPendingInitialEditFetch)
    ) {
      if (shouldRunPendingInitialEditFetch) {
        pendingInitialEditFetchRouteIdRef.current = null;
        pendingInitialEditFetchCoordsRef.current = '';
        pendingInitialEditFetchProfileRef.current = '';
      }

      void fetchRouteForHandles(routePoints, undefined);
      return;
    }

    if (routePoints.length < 2) {
      setRouteData(null);
      setTurnPoints(null);
      setIsRouteTooLong(false);
    }
  }, [
    editRouteId,
    fetchRouteForHandles,
    isRouteDraggingRef,
    isRouteLoadingFromCacheRef,
    pendingInitialEditFetchCoordsRef,
    pendingInitialEditFetchProfileRef,
    pendingInitialEditFetchRouteIdRef,
    previousRoutePointsCoordsRef,
    previousRoutingProfileRef,
    routePoints,
    routingProfile,
    setIsRouteTooLong,
    setRouteData,
    setTurnPoints,
  ]);

  useEffect(() => {
    setSelectedRouteName('');
  }, [routingProfile, setSelectedRouteName]);

  useEffect(() => {
    if (isRouteNameManuallySet || routePoints.length === 0) {
      return;
    }

    const locations = routePoints
      .map(point => extractLocationName(point.displayName))
      .filter((name): name is string => name !== null);

    if (locations.length === 1) {
      setAutoGeneratedRouteName(locations[0]);
      return;
    }

    if (locations.length >= 2) {
      const firstName = locations[0];
      const lastName = locations[locations.length - 1];

      if (firstName && lastName && firstName !== lastName) {
        setAutoGeneratedRouteName(`${firstName} - ${lastName}`);
      } else if (firstName) {
        setAutoGeneratedRouteName(firstName);
      }
    }
  }, [isRouteNameManuallySet, routePoints, setAutoGeneratedRouteName]);
};
