import { useCallback, useEffect, useRef, useState } from 'react';
import type { MutableRefObject, RefObject } from 'react';
import type { FeatureCollection, GeoJsonProperties, LineString } from 'geojson';
import { useSearchParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { reverseGeocode } from '../../../services/localProjects';
import {
  cacheRoadbookForOffline,
  type RoadbookCacheProgress,
} from '../../../utils/cacheRoadbookForOffline';
import { calculateDistance } from '../../../utils/calcDistance';
import { generateRandomColor } from '../../../utils/colorUtils';
import { processGPXFile } from '../../../utils/gpxParser';
import { useAppStore } from '../../../stores/appStore';
import { useRoutesStore } from '../../../stores/routesStore';
import type { RoutePoint } from '../types';
import {
  createStraightLineRoute,
  DISTANCE_WARNING_TIMEOUT_MS,
  findRouteInsertIndex,
  isClickNearExistingPoint,
} from '../utils/routeBuilderUtils';
import {
  useRouteBuilderState,
  useRouteBuilderStoreActions,
} from './useRouteBuilderStore';

type RouteLineData = FeatureCollection<LineString, GeoJsonProperties> | null;
interface UseRouteBuilderActionsArgs {
  editRouteId?: string;
  isRouteDraggingRef: MutableRefObject<boolean>;
  isRouteLoadingFromCacheRef: MutableRefObject<boolean>;
  mapMoveTimeoutRef: MutableRefObject<NodeJS.Timeout | null>;
  mapRef: RefObject<any>;
  onRouteGenerated: (
    routeData: FeatureCollection<LineString, GeoJsonProperties>,
    routeName: string,
    routeId?: string,
    waypoints?: { lat: number; lon: number }[],
    profile?: string
  ) => void;
  setRouteNameInput: (name: string) => void;
}

export const useRouteBuilderActions = ({
  editRouteId,
  isRouteDraggingRef,
  isRouteLoadingFromCacheRef,
  mapMoveTimeoutRef,
  mapRef,
  onRouteGenerated,
  setRouteNameInput,
}: UseRouteBuilderActionsArgs) => {
  const { t } = useTranslation();
  const [generationProgress, setGenerationProgress] =
    useState<RoadbookCacheProgress | null>(null);
  const [, setSearchParams] = useSearchParams();
  const { routeData, routePoints, routingProfile, selectedRouteName } =
    useRouteBuilderState();
  const {
    setAutoGeneratedRouteName,
    setError,
    setGpxUnderlay,
    setIsRouteLoading,
    setIsRouteNameManuallySet,
    setLoadingRouteData,
    setRouteData,
    setRoutePoints,
    setSelectedRouteName,
    setStoredMapView,
    setTurnPoints,
  } = useRouteBuilderStoreActions();
  const routesStore = useRoutesStore();
  const isEditMode = Boolean(editRouteId);
  const [distanceWarning, setDistanceWarning] = useState<string | null>(null);
  const [isGettingLocation, setIsGettingLocation] = useState(false);
  const warningTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    return () => {
      if (warningTimeoutRef.current) {
        clearTimeout(warningTimeoutRef.current);
      }
      if (mapMoveTimeoutRef.current) {
        clearTimeout(mapMoveTimeoutRef.current);
      }
    };
  }, [mapMoveTimeoutRef]);

  const showDistanceWarning = (message: string) => {
    setDistanceWarning(message);

    if (warningTimeoutRef.current) {
      clearTimeout(warningTimeoutRef.current);
    }

    warningTimeoutRef.current = setTimeout(() => {
      setDistanceWarning(null);
    }, DISTANCE_WARNING_TIMEOUT_MS);
  };

  const clearDistanceWarning = () => {
    if (warningTimeoutRef.current) {
      clearTimeout(warningTimeoutRef.current);
      warningTimeoutRef.current = null;
    }

    setDistanceWarning(null);
  };

  const markRouteAsUnsaved = (resetCacheLoading = false) => {
    if (resetCacheLoading) {
      isRouteLoadingFromCacheRef.current = false;
    }

    if (selectedRouteName) {
      setSelectedRouteName('');
    }
  };

  const reverseGeocodePoint = (
    pointId: string,
    lat: number,
    lon: number,
    errorMessage: string
  ) => {
    reverseGeocode(lat, lon)
      .then(result => {
        const currentPoints = useAppStore.getState().routeBuilderPoints;
        const updatedPoints = currentPoints.map((point: RoutePoint) =>
          point.id === pointId && point.lat === lat && point.lon === lon
            ? { ...point, displayName: result.displayName }
            : point
        );
        setRoutePoints(updatedPoints);
      })
      .catch(error => {
        console.error(errorMessage, error);
      });
  };

  const createPoint = (
    lat: number,
    lon: number,
    displayName?: string,
    idPrefix = 'point'
  ): RoutePoint => ({
    id: `${idPrefix}_${Date.now()}`,
    lat,
    lon,
    color: generateRandomColor(),
    displayName,
  });

  const validateInsertDistance = (
    lat: number,
    lon: number,
    insertIndex: number
  ) => {
    if (routePoints.length === 0) {
      return true;
    }

    const maxDistanceKm = 40_000;
    const maxDistanceMeters = maxDistanceKm * 1000;
    const nearbyPoint =
      insertIndex > 0 ? routePoints[insertIndex - 1] : routePoints[0];
    const distanceToNearby = calculateDistance(
      nearbyPoint.lat,
      nearbyPoint.lon,
      lat,
      lon
    );

    if (distanceToNearby > maxDistanceMeters) {
      showDistanceWarning(
        t('routeBuilder:warnings.pointTooFar', {
          distance: (distanceToNearby / 1000).toFixed(1),
          maxDistance: maxDistanceKm,
        })
      );
      return false;
    }

    return true;
  };

  const addPoint = (lng: number, lat: number) => {
    markRouteAsUnsaved(true);

    if (isClickNearExistingPoint({ lng, lat, routePoints, mapRef })) {
      return;
    }

    const insertIndex = findRouteInsertIndex({
      lng,
      lat,
      routePoints,
      routeData,
      mapRef,
    });

    if (!validateInsertDistance(lat, lng, insertIndex)) {
      return;
    }

    const newPoint = createPoint(lat, lng);
    const updatedPoints = [...routePoints];
    updatedPoints.splice(insertIndex, 0, newPoint);
    setRoutePoints(updatedPoints);
    clearDistanceWarning();
    reverseGeocodePoint(newPoint.id, lat, lng, 'Error reverse geocoding:');
  };

  const addCurrentPosition = () => {
    if (isGettingLocation) {
      return;
    }

    setIsGettingLocation(true);
    navigator.geolocation.getCurrentPosition(
      position => {
        addPoint(position.coords.longitude, position.coords.latitude);
        setIsGettingLocation(false);
      },
      error => {
        console.error('Error getting location:', error);
        setError(t('errors.locationError'));
        setIsGettingLocation(false);
      },
      { enableHighAccuracy: true, timeout: 10000, maximumAge: 60000 }
    );
  };

  const addPointByAddress = (
    lat: number,
    lon: number,
    displayName?: string
  ) => {
    const isFirstPoint = routePoints.length === 0;
    const maxDistanceKm = 40_000;
    const maxDistanceMeters = maxDistanceKm * 1000;

    if (routePoints.length > 0) {
      const lastPoint = routePoints[routePoints.length - 1];
      const distanceToLast = calculateDistance(
        lastPoint.lat,
        lastPoint.lon,
        lat,
        lon
      );

      if (distanceToLast > maxDistanceMeters) {
        showDistanceWarning(
          t('routeBuilder:warnings.pointTooFar', {
            distance: (distanceToLast / 1000).toFixed(1),
            maxDistance: maxDistanceKm,
          })
        );
        return;
      }
    }

    if (!displayName) {
      addPoint(lon, lat);
      return;
    }

    markRouteAsUnsaved(true);
    const newPoint = createPoint(lat, lon, displayName);
    setRoutePoints([...routePoints, newPoint]);
    clearDistanceWarning();

    if (isFirstPoint) {
      mapRef.current?.flyTo?.({
        center: [lon, lat],
        zoom: 15,
        duration: 1000,
      });
    }
  };

  const updatePoint = (id: string, lat: number, lng: number) => {
    isRouteDraggingRef.current = false;
    markRouteAsUnsaved();

    const maxDistanceKm = 40_000;
    const maxDistanceMeters = maxDistanceKm * 1000;
    const pointIndex = routePoints.findIndex(point => point.id === id);
    if (pointIndex === -1) {
      return;
    }

    if (pointIndex > 0) {
      const prevPoint = routePoints[pointIndex - 1];
      const distanceToPrev = calculateDistance(
        prevPoint.lat,
        prevPoint.lon,
        lat,
        lng
      );

      if (distanceToPrev > maxDistanceMeters) {
        showDistanceWarning(
          t('routeBuilder:warnings.pointTooFarFromOthers', {
            distance: (distanceToPrev / 1000).toFixed(1),
            maxDistance: maxDistanceKm,
          })
        );
        return;
      }
    }

    if (pointIndex < routePoints.length - 1) {
      const nextPoint = routePoints[pointIndex + 1];
      const distanceToNext = calculateDistance(
        nextPoint.lat,
        nextPoint.lon,
        lat,
        lng
      );

      if (distanceToNext > maxDistanceMeters) {
        showDistanceWarning(
          t('routeBuilder:warnings.pointTooFarFromOthers', {
            distance: (distanceToNext / 1000).toFixed(1),
            maxDistance: maxDistanceKm,
          })
        );
        return;
      }
    }

    setRoutePoints(
      routePoints.map(point =>
        point.id === id
          ? { ...point, lat, lon: lng, displayName: undefined }
          : point
      )
    );
    reverseGeocodePoint(id, lat, lng, 'Error reverse geocoding updated point:');
  };

  const removePoint = (id: string) => {
    markRouteAsUnsaved();

    const updatedPoints = routePoints.filter(point => point.id !== id);
    setRoutePoints(updatedPoints);

    if (updatedPoints.length === 0) {
      setAutoGeneratedRouteName('');
      setIsRouteNameManuallySet(false);
      setRouteNameInput('');
    }
  };

  const handleMarkerDragStart = (_id: string) => {
    setRouteData(null);
    setTurnPoints(null);
    setLoadingRouteData(createStraightLineRoute(routePoints));
    isRouteDraggingRef.current = true;
  };

  const handleRouteClick = (lng: number, lat: number) => {
    markRouteAsUnsaved(true);

    const insertIndex = findRouteInsertIndex({
      lng,
      lat,
      routePoints,
      routeData,
      mapRef,
    });

    if (!validateInsertDistance(lat, lng, insertIndex)) {
      return;
    }

    const newPoint = createPoint(lat, lng);
    const updatedPoints = [...routePoints];
    updatedPoints.splice(insertIndex, 0, newPoint);
    setRoutePoints(updatedPoints);
    clearDistanceWarning();
    reverseGeocodePoint(newPoint.id, lat, lng, 'Error reverse geocoding:');
  };

  const handleRouteMouseDown = (lng: number, lat: number) => {
    markRouteAsUnsaved(true);

    const insertIndex = findRouteInsertIndex({
      lng,
      lat,
      routePoints,
      routeData,
      mapRef,
    });

    if (!validateInsertDistance(lat, lng, insertIndex)) {
      return null;
    }

    const newPoint = createPoint(lat, lng);
    const updatedPoints = [...routePoints];
    updatedPoints.splice(insertIndex, 0, newPoint);
    setRoutePoints(updatedPoints);
    setRouteData(null);
    setTurnPoints(null);
    setLoadingRouteData(createStraightLineRoute(updatedPoints));
    isRouteDraggingRef.current = true;
    clearDistanceWarning();

    return newPoint.id;
  };

  const handleRouteDragMove = (
    _pointId: string,
    _lng: number,
    _lat: number
  ) => {};

  const handleRouteDragEnd = (pointId: string, lng: number, lat: number) => {
    isRouteDraggingRef.current = false;
    setRoutePoints(
      routePoints.map(point =>
        point.id === pointId
          ? { ...point, lat, lon: lng, displayName: undefined }
          : point
      )
    );
    reverseGeocodePoint(
      pointId,
      lat,
      lng,
      'Error reverse geocoding dragged point:'
    );
  };

  const clearPoints = () => {
    markRouteAsUnsaved(true);
    setAutoGeneratedRouteName('');
    setIsRouteNameManuallySet(false);
    setRouteNameInput('');
    setRoutePoints([]);
    setRouteData(null);
    setTurnPoints(null);
    setGpxUnderlay(null);
  };

  const handleGPXImport = async (file: File) => {
    try {
      setError(null);
      setIsRouteLoading(true);

      const { originalGeoJSON, waypoints } = await processGPXFile(file, {
        simplifyTolerance: 0.01,
        maxWaypoints: 200,
      });

      setGpxUnderlay(originalGeoJSON as RouteLineData);
      setRoutePoints([]);
      setRouteData(null);
      setTurnPoints(null);

      const importId = Date.now();
      const newPoints: RoutePoint[] = waypoints.map((waypoint, index) => ({
        id: `gpx_point_${importId}_${index}`,
        lat: waypoint.lat,
        lon: waypoint.lon,
        color: generateRandomColor(),
        displayName: undefined,
      }));

      setRoutePoints(newPoints);
      isRouteLoadingFromCacheRef.current = false;
      setIsRouteNameManuallySet(false);
      setAutoGeneratedRouteName('');

      if (waypoints.length > 0) {
        reverseGeocodePoint(
          newPoints[0].id,
          waypoints[0].lat,
          waypoints[0].lon,
          'Error reverse geocoding first GPX point:'
        );

        if (waypoints.length > 1) {
          const lastIndex = waypoints.length - 1;
          reverseGeocodePoint(
            newPoints[lastIndex].id,
            waypoints[lastIndex].lat,
            waypoints[lastIndex].lon,
            'Error reverse geocoding last GPX point:'
          );
        }
      }

      if (waypoints.length > 0) {
        try {
          const map = mapRef.current?.getMap?.();
          if (map?.fitBounds) {
            let minLng = waypoints[0].lon;
            let maxLng = waypoints[0].lon;
            let minLat = waypoints[0].lat;
            let maxLat = waypoints[0].lat;

            waypoints.forEach(waypoint => {
              minLng = Math.min(minLng, waypoint.lon);
              maxLng = Math.max(maxLng, waypoint.lon);
              minLat = Math.min(minLat, waypoint.lat);
              maxLat = Math.max(maxLat, waypoint.lat);
            });

            map.fitBounds(
              [
                [minLng, minLat],
                [maxLng, maxLat],
              ],
              { padding: 50, duration: 1000 }
            );
          }
        } catch (error) {
          console.error('Error zooming to GPX bounds:', error);
        }
      }
    } catch (error) {
      console.error('Error importing GPX:', error);
      setError(
        error instanceof Error
          ? `GPX Import Fehler: ${error.message}`
          : 'Fehler beim Importieren der GPX-Datei'
      );
      setGpxUnderlay(null);
    } finally {
      setIsRouteLoading(false);
    }
  };

  const handleMapMove = useCallback(
    (viewState: { latitude: number; longitude: number; zoom: number }) => {
      setStoredMapView(viewState);

      if (mapMoveTimeoutRef.current) {
        clearTimeout(mapMoveTimeoutRef.current);
      }

      mapMoveTimeoutRef.current = setTimeout(() => {
        const newParams = new URLSearchParams(window.location.search);
        newParams.set('lat', viewState.latitude.toFixed(4));
        newParams.set('lng', viewState.longitude.toFixed(4));
        newParams.set('zoom', viewState.zoom.toFixed(2));
        setSearchParams(newParams, { replace: true });
      }, 500);
    },
    [mapMoveTimeoutRef, setSearchParams, setStoredMapView]
  );

  const reorderPoints = (reorderedPoints: RoutePoint[]) => {
    markRouteAsUnsaved(true);
    setRoutePoints(reorderedPoints);
  };

  const generateRoute = async (routeName: string) => {
    if (!routeData || routePoints.length < 2) {
      return;
    }

    try {
      const routePointsData = routePoints.map(point => ({
        lat: point.lat,
        lon: point.lon,
      }));

      const savedRoute =
        isEditMode && editRouteId
          ? await routesStore.updateRoute(editRouteId, {
              name: routeName,
              waypoints: routePointsData,
              profile: routingProfile,
              cached_brouterTrack_data: routeData,
              total_turns: 0,
            })
          : await routesStore.saveRoute({
              name: routeName,
              waypoints: routePointsData,
              profile: routingProfile,
              cached_brouterTrack_data: routeData,
              total_turns: 0,
            });

      if (isEditMode) {
        try {
          await cacheRoadbookForOffline({
            routeId: savedRoute.id,
            routeName: savedRoute.name,
            profile: savedRoute.profile || routingProfile,
            onProgress: progress => setGenerationProgress(progress),
          });
        } catch (cacheError) {
          console.warn(
            `Failed to pre-cache roadbook ${savedRoute.id} after save:`,
            cacheError
          );
        } finally {
          setGenerationProgress(null);
        }
      }

      setSelectedRouteName(savedRoute.name);
      onRouteGenerated(
        routeData,
        savedRoute.name,
        savedRoute.id,
        routePoints.map(point => ({ lat: point.lat, lon: point.lon })),
        routingProfile
      );
      setRouteNameInput('');
    } catch (error: any) {
      console.error('Failed to save route:', error);

      if (error.response?.data?.error) {
        setError(error.response.data.message || error.response.data.error);
      } else {
        setError(
          error instanceof Error ? error.message : t('errors.routeSaveError')
        );
      }
    }
  };

  return {
    addCurrentPosition,

    addPoint,
    addPointByAddress,
    generationProgress,
    clearPoints,
    distanceWarning,
    generateRoute,
    handleGPXImport,
    handleMapMove,
    handleMarkerDragStart,
    handleRouteClick,
    handleRouteDragEnd,
    handleRouteDragMove,
    handleRouteMouseDown,
    isGettingLocation,
    removePoint,
    reorderPoints,
    updatePoint,
  };
};
