import { useShallow } from 'zustand/react/shallow';
import { useAppStore } from '../../../stores/appStore';

export const useRouteBuilderState = () =>
  useAppStore(
    useShallow(state => ({
      routePoints: state.routeBuilderPoints,
      routeData: state.routeBuilderData,
      turnPoints: state.routeBuilderTurnPoints,
      loadingRouteData: state.routeBuilderLoadingData,
      isRouteLoading: state.routeBuilderIsLoading,
      error: state.routeBuilderError,
      selectedRouteName: state.routeBuilderSelectedName,
      routingProfile: state.routeBuilderProfile,
      autoGeneratedRouteName: state.routeBuilderAutoGeneratedName,
      isRouteNameManuallySet: state.routeBuilderIsNameManuallySet,
      storedMapView: state.routeBuilderMapView,
      gpxUnderlay: state.routeBuilderGpxUnderlay,
    }))
  );

export const useRouteBuilderStoreActions = () =>
  useAppStore(
    useShallow(state => ({
      setRoutePoints: state.setRouteBuilderPoints,
      setRouteData: state.setRouteBuilderData,
      setTurnPoints: state.setRouteBuilderTurnPoints,
      setLoadingRouteData: state.setRouteBuilderLoadingData,
      setIsRouteLoading: state.setRouteBuilderIsLoading,
      setError: state.setRouteBuilderError,
      setSelectedRouteName: state.setRouteBuilderSelectedName,
      setRoutingProfile: state.setRouteBuilderProfile,
      setAutoGeneratedRouteName: state.setRouteBuilderAutoGeneratedName,
      setIsRouteNameManuallySet: state.setRouteBuilderIsNameManuallySet,
      setStoredMapView: state.setRouteBuilderMapView,
      setGpxUnderlay: state.setRouteBuilderGpxUnderlay,
    }))
  );
