import React, { createContext, useContext } from 'react';
import type { RefObject } from 'react';
import type {
  FeatureCollection,
  GeoJsonProperties,
  LineString,
  Point,
} from 'geojson';
import type { RouteBuilderMapView } from './utils/routeBuilderUtils';
import type { RoutePoint } from './types';

type RouteLineData = FeatureCollection<LineString, GeoJsonProperties> | null;
type TurnPointData = FeatureCollection<Point, GeoJsonProperties> | null;

export interface RouteBuilderControllerValue {
  autoGeneratedRouteName: string;
  addCurrentPosition: () => void;
  addPoint: (lng: number, lat: number) => void;
  addPointByAddress: (lat: number, lon: number, displayName?: string) => void;
  clearPoints: () => void;
  error: string | null;
  generateRoute: (routeName: string) => Promise<void>;
  gpxUnderlay: RouteLineData;
  hasPendingChanges: boolean;
  handleGPXImport: (file: File) => Promise<void>;
  handleMapMove: (viewState: RouteBuilderMapView) => void;
  handleMarkerDragStart: (id: string) => void;
  handleRouteClick: (lng: number, lat: number) => void;
  handleRouteDragEnd: (pointId: string, lng: number, lat: number) => void;
  handleRouteDragMove: (pointId: string, lng: number, lat: number) => void;
  handleRouteMouseDown: (lng: number, lat: number) => string | null;
  initialViewState: RouteBuilderMapView;
  isGettingLocation: boolean;
  isEditMode: boolean;
  isRouteLoading: boolean;
  isRouteNameManuallySet: boolean;
  isRouteTooLong: boolean;
  isSidebarCollapsed: boolean;
  loadingRouteData: RouteLineData;
  mapRef: RefObject<any>;
  reloadCurrentRoute: () => void;
  removePoint: (id: string) => void;
  reorderPoints: (points: RoutePoint[]) => void;
  routeData: RouteLineData;
  routeNameInput: string;
  routePoints: RoutePoint[];
  routingProfile: string;
  setIsRouteNameManuallySet: (isSet: boolean) => void;
  setRouteNameInput: (name: string) => void;
  setRoutingProfile: (profile: string) => void;
  submitLabel: string;
  submitLoadingLabel: string;
  generationProgress: { text: string; percent?: number } | null;
  toggleSidebar: () => void;
  turnPoints: TurnPointData;
  updatePoint: (id: string, lat: number, lng: number) => void;
}

const RouteBuilderControllerContext =
  createContext<RouteBuilderControllerValue | null>(null);

interface RouteBuilderControllerProviderProps {
  children: React.ReactNode;
  value: RouteBuilderControllerValue;
}

export const RouteBuilderControllerProvider: React.FC<
  RouteBuilderControllerProviderProps
> = ({ children, value }) => {
  return (
    <RouteBuilderControllerContext.Provider value={value}>
      {children}
    </RouteBuilderControllerContext.Provider>
  );
};

export const useRouteBuilderController = () => {
  const context = useContext(RouteBuilderControllerContext);

  if (!context) {
    throw new Error(
      'useRouteBuilderController must be used within RouteBuilderControllerProvider'
    );
  }

  return context;
};
