import { routeSurfacePreview } from './utils/routeSurfaces';
import React, { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Map, AttributionControl, ScaleControl } from 'react-map-gl/maplibre';
import 'maplibre-gl/dist/maplibre-gl.css';
import {
  Box,
  Button,
  CloseButton,
  Dialog,
  Input,
  Portal,
  Text,
  VStack,
} from '@chakra-ui/react';
import { FeatureCollection, LineString } from 'geojson';
import { useMapColors } from '../../theme/colors';
import { useAppStore } from '../../stores/appStore';
import { useSettings } from '../../stores/settingsStore';
import { useRouteBuilderController } from './RouteBuilderControllerContext';
import {
  getMapStyleAttributionHtml,
  getMapStyleSpec,
  type MapStyleId,
} from './mapStyles';
import { RouteMapControls } from './RouteMapControls';
import { RouteMapGenerateAction } from './RouteMapGenerateAction';
import { RouteMapLayers } from './RouteMapLayers';
import { RouteMapMarkers } from './RouteMapMarkers';
import { RouteMapStatusOverlays } from './RouteMapStatusOverlays';
import { useRouteMapInteractions } from './hooks/useRouteMapInteractions';
import { computeRouteAnalysis } from './utils/routeAnalysis';
import { normalizeSurfaceKey } from './utils/surfaces';

const RouteMap: React.FC = () => {
  const { t } = useTranslation();
  const {
    autoGeneratedRouteName,
    addPoint,
    error,
    generateRoute,
    gpxUnderlay,
    hasPendingChanges,
    handleMapMove,
    handleMarkerDragStart,
    handleRouteClick,
    handleRouteDragEnd,
    handleRouteDragMove,
    handleRouteMouseDown,
    initialViewState,
    isEditMode,
    isRouteLoading,
    isRouteTooLong,
    loadingRouteData,
    mapRef,
    reloadCurrentRoute,
    removePoint,
    routeData,
    routeNameInput,
    routePoints,
    setIsRouteNameManuallySet,
    setRouteNameInput,
    submitLabel,
    submitLoadingLabel,
    generationProgress,
    turnPoints,
    updatePoint,
  } = useRouteBuilderController();

  const mapColors = useMapColors();
  const currentPosition = useAppStore(
    state => state.navigation.currentPosition
  );
  const requestInitialLocation = useAppStore(
    state => state.requestInitialLocation
  );
  const settingsStore = useSettings();
  const persistedMapStyle =
    (settingsStore.app.defaultMapStyle as MapStyleId | undefined) ??
    'open_street_map';
  const [mapStyle, setMapStyleState] = useState<MapStyleId>(persistedMapStyle);

  const setMapStyle = (style: MapStyleId) => {
    setMapStyleState(style);
    void settingsStore.updateAppSettings({ defaultMapStyle: style });
  };
  const [mapLoaded, setMapLoaded] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isAnalysisOpen, setIsAnalysisOpen] = useState(false);
  const [isSaveDialogOpen, setIsSaveDialogOpen] = useState(false);
  const [pendingRouteName, setPendingRouteName] = useState('');
  const [hoveredSurfaceKey, setHoveredSurfaceKey] = useState<string | null>(
    null
  );
  const [isLoadingLocation, setIsLoadingLocation] = useState(false);

  useEffect(() => {
    setMapStyleState(currentMapStyle =>
      currentMapStyle === persistedMapStyle
        ? currentMapStyle
        : persistedMapStyle
    );
  }, [persistedMapStyle]);

  const mapStyleSpec = useMemo(() => getMapStyleSpec(mapStyle), [mapStyle]);
  const attributionHtml = useMemo(
    () => getMapStyleAttributionHtml(mapStyle),
    [mapStyle]
  );

  const {
    effectiveLoadingRouteData,
    effectiveRoutePoints,
    hoverInfo,
    onMapClick,
    onMapMouseDown,
    onMapMouseMove,
    onMapMouseUp,
    onMarkerClick,
    onMarkerDrag,
    onMarkerDragEnd,
    onMarkerDragStart,
  } = useRouteMapInteractions({
    addPoint,
    handleMarkerDragStart,
    handleRouteClick,
    handleRouteDragEnd,
    handleRouteDragMove,
    handleRouteMouseDown,
    isLoading: isRouteLoading,
    loadingRouteData,
    removePoint,
    routeData,
    routePoints,
    t,
    updatePoint,
  });

  const normalizedRouteData = useMemo(() => {
    if (!routeData) {
      return null;
    }

    return {
      ...routeData,
      features: (routeSurfacePreview(routeData).features || []).map(
        (feature: any) => {
          const surfaceRaw = feature?.properties?.surface || 'unknown';
          const surfaceNorm = normalizeSurfaceKey(surfaceRaw);

          return {
            ...feature,
            properties: {
              ...(feature.properties || {}),
              surface_norm: surfaceNorm,
            },
          };
        }
      ),
    } as FeatureCollection<LineString>;
  }, [routeData]);

  const { routeStats, routeLineColor } = useMemo(
    () => computeRouteAnalysis(normalizedRouteData as any, turnPoints as any),
    [normalizedRouteData, turnPoints]
  );

  useEffect(() => {
    if (!routeStats) {
      setIsAnalysisOpen(false);
    }
  }, [routeStats]);

  useEffect(() => {
    const map = mapRef.current?.getMap?.();
    if (!map) {
      return undefined;
    }

    const registerPattern = () => {};

    map.setPitch(
      (map.getStyle().metadata as Record<string, unknown>)?.['roadbooknavi:3d']
        ? 60
        : 0
    );
    registerPattern();
    map.on('load', registerPattern);
    map.on('styledata', registerPattern);

    return () => {
      map.off('load', registerPattern);
      map.off('styledata', registerPattern);
    };
  }, [mapRef, mapStyleSpec, mapLoaded]);

  const zoomToCurrentLocation = async () => {
    setIsLoadingLocation(true);
    try {
      await requestInitialLocation();
      const position = useAppStore.getState().navigation.currentPosition;

      if (position && mapRef.current) {
        mapRef.current.flyTo({
          center: [position.longitude, position.latitude],
          zoom: 15,
          duration: 1000,
        });
      }
    } catch (error) {
      console.error('Error getting current location:', error);
    } finally {
      setIsLoadingLocation(false);
    }
  };

  const handleConfirmSave = async () => {
    const trimmedRouteName = pendingRouteName.trim();
    if (!trimmedRouteName || isGenerating || isRouteLoading) {
      return;
    }

    setIsGenerating(true);
    try {
      setRouteNameInput(trimmedRouteName);
      setIsRouteNameManuallySet(true);
      await generateRoute(trimmedRouteName);
      setIsSaveDialogOpen(false);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleGenerateAction = async () => {
    if (
      routePoints.length < 2 ||
      !routeData ||
      isRouteLoading ||
      isGenerating ||
      isRouteTooLong
    ) {
      return;
    }

    if (isEditMode && routeNameInput.trim()) {
      setIsGenerating(true);
      try {
        await generateRoute(routeNameInput.trim());
      } finally {
        setIsGenerating(false);
      }
      return;
    }

    setPendingRouteName(routeNameInput.trim() || autoGeneratedRouteName.trim());
    setIsSaveDialogOpen(true);
  };

  return (
    <>
      <Box
        position="relative"
        height="100%"
        width="100%"
        borderRadius="md"
        overflow="hidden"
        borderWidth="1px"
        borderColor={mapColors.borderColor}
      >
        <Map
          ref={mapRef}
          onLoad={() => setMapLoaded(true)}
          initialViewState={
            initialViewState ||
            (currentPosition
              ? {
                  longitude: currentPosition.longitude,
                  latitude: currentPosition.latitude,
                  zoom: 12,
                }
              : {
                  longitude: 10.4515,
                  latitude: 51.1657,
                  zoom: 6,
                })
          }
          onMoveEnd={event => {
            const viewState = event.viewState;
            handleMapMove({
              latitude: viewState.latitude,
              longitude: viewState.longitude,
              zoom: viewState.zoom,
            });
          }}
          attributionControl={false}
          style={{ width: '100%', height: '100%' }}
          mapStyle={mapStyleSpec as any}
          interactiveLayerIds={['route-line', 'route-line-highlight']}
          onMouseDown={onMapMouseDown}
          onMouseMove={onMapMouseMove}
          onMouseUp={onMapMouseUp}
          onClick={onMapClick}
        >
          <AttributionControl
            compact
            style={{
              background: mapColors.attributionBg,
              fontSize: '10px',
              padding: '2px 4px',
            }}
            customAttribution={attributionHtml}
          />
          <ScaleControl position="top-left" />
          <RouteMapMarkers
            isLoading={isRouteLoading}
            routePoints={effectiveRoutePoints}
            onMarkerClick={onMarkerClick}
            onMarkerDrag={onMarkerDrag}
            onMarkerDragEnd={onMarkerDragEnd}
            onMarkerDragStart={onMarkerDragStart}
          />

          <RouteMapLayers
            effectiveLoadingRouteData={effectiveLoadingRouteData}
            gpxUnderlay={gpxUnderlay}
            hoveredSurfaceKey={hoveredSurfaceKey}
            loadingRouteData={loadingRouteData}
            normalizedRouteData={normalizedRouteData}
            routeLineColor={routeLineColor}
            turnPoints={turnPoints}
          />
        </Map>

        <RouteMapStatusOverlays
          hoverInfo={hoverInfo}
          isLoading={isRouteLoading}
          routeStats={routeStats}
          isAnalysisOpen={isAnalysisOpen}
          onAnalysisOpenChange={setIsAnalysisOpen}
          onSurfaceHoverChange={setHoveredSurfaceKey}
          error={error}
        />

        <RouteMapControls
          isLoading={isRouteLoading}
          isLoadingLocation={isLoadingLocation}
          mapRef={mapRef}
          mapStyle={mapStyle}
          onZoomToCurrentLocation={zoomToCurrentLocation}
          setMapStyle={setMapStyle}
        />

        <RouteMapGenerateAction
          hasRouteData={Boolean(routeData)}
          hasPendingChanges={hasPendingChanges}
          isAnalysisOpen={isAnalysisOpen}
          isEditMode={isEditMode}
          isGenerating={isGenerating}
          isLoading={isRouteLoading}
          isRouteTooLong={isRouteTooLong}
          onAnalysisToggle={() => setIsAnalysisOpen(prev => !prev)}
          onGenerateRoute={handleGenerateAction}
          onUndoChanges={reloadCurrentRoute}
          routePointsCount={routePoints.length}
          routeStats={routeStats}
          submitLabel={submitLabel}
          submitLoadingLabel={
            generationProgress
              ? `${generationProgress.text}${generationProgress.percent != null ? ` (${generationProgress.percent}%)` : ''}`
              : submitLoadingLabel
          }
        />
      </Box>

      <Dialog.Root
        open={isSaveDialogOpen}
        onOpenChange={details => {
          if (isGenerating) {
            return;
          }

          setIsSaveDialogOpen(details.open);
        }}
      >
        <Portal>
          <Dialog.Backdrop />
          <Dialog.Positioner>
            <Dialog.Content>
              <Dialog.Header>
                <Dialog.Title>
                  {t('routeBuilder:dialogs.saveTitle')}
                </Dialog.Title>
              </Dialog.Header>
              <Dialog.Body>
                <VStack align="stretch" gap={4}>
                  <Text>{t('routeBuilder:dialogs.saveDescription')}</Text>
                  <Input
                    value={pendingRouteName}
                    onChange={event => setPendingRouteName(event.target.value)}
                    placeholder={
                      t('routeBuilder:labels.roadbookName') ||
                      'Enter roadbook name...'
                    }
                    autoFocus
                    onKeyDown={event => {
                      if (event.key === 'Enter') {
                        event.preventDefault();
                        void handleConfirmSave();
                      }
                    }}
                  />
                </VStack>
              </Dialog.Body>
              <Dialog.Footer>
                <Button
                  variant="outline"
                  onClick={() => setIsSaveDialogOpen(false)}
                  disabled={isGenerating}
                  mr={3}
                >
                  {t('common.cancel')}
                </Button>
                <Button
                  colorScheme="blue"
                  onClick={() => void handleConfirmSave()}
                  loading={isGenerating}
                  disabled={!pendingRouteName.trim()}
                >
                  {t('common.save')}
                </Button>
              </Dialog.Footer>
              <Dialog.CloseTrigger asChild>
                <CloseButton size="sm" disabled={isGenerating} />
              </Dialog.CloseTrigger>
            </Dialog.Content>
          </Dialog.Positioner>
        </Portal>
      </Dialog.Root>
    </>
  );
};

export default RouteMap;
