import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useLocation, useParams, useSearchParams } from 'react-router-dom';
import { Box, Flex, IconButton } from '@chakra-ui/react';
import { useTranslation } from 'react-i18next';
import { FeatureCollection, GeoJsonProperties, LineString } from 'geojson';
import { useUIColors } from '../../theme/colors';
import { generateRandomColor } from '../../utils/colorUtils';
import { useRoutesStore } from '../../stores/routesStore';
import { useSettings } from '../../stores/settingsStore';
import RouteMap from './RouteMap';
import { RouteBuilderSidebar } from './RouteBuilderSidebar';
import {
  RouteBuilderControllerProvider,
  type RouteBuilderControllerValue,
} from './RouteBuilderControllerContext';
import { useRouteBuilderActions } from './hooks/useRouteBuilderActions';
import { useRouteBuilderEffects } from './hooks/useRouteBuilderEffects';
import {
  useRouteBuilderState,
  useRouteBuilderStoreActions,
} from './hooks/useRouteBuilderStore';
import {
  RouteBuilderMapView,
  buildRoutePointsCoordsString,
  getInitialRouteBuilderView,
} from './utils/routeBuilderUtils';
import { getAppSectionFromPathname } from '../../utils/roadbookRoute';

interface RouteBuilderProps {
  onRouteGenerated: (
    routeData: FeatureCollection<LineString, GeoJsonProperties>,
    routeName: string,
    routeId?: string,
    waypoints?: { lat: number; lon: number }[],
    profile?: string
  ) => void;
}

export const RouteBuilder: React.FC<RouteBuilderProps> = ({
  onRouteGenerated,
}) => {
  const uiColors = useUIColors();
  const { t } = useTranslation();
  const location = useLocation();
  const { editRouteId: routeEditId } = useParams<{ editRouteId?: string }>();
  const retainedEditRouteIdRef = useRef<string | undefined>(routeEditId);
  if (getAppSectionFromPathname(location.pathname) === 'route-planning') {
    retainedEditRouteIdRef.current = routeEditId;
  }
  const editRouteId = retainedEditRouteIdRef.current;
  const [searchParams] = useSearchParams();
  const {
    autoGeneratedRouteName,
    error,
    gpxUnderlay,
    isRouteLoading,
    isRouteNameManuallySet,
    loadingRouteData,
    routeData,
    routePoints,
    routingProfile,
    storedMapView,
    turnPoints,
  } = useRouteBuilderState();
  const {
    setAutoGeneratedRouteName,
    setError,
    setGpxUnderlay,
    setIsRouteLoading,
    setIsRouteNameManuallySet,
    setLoadingRouteData,
    setRouteData,
    setRoutePoints,
    setRoutingProfile,
    setSelectedRouteName,
    setTurnPoints,
  } = useRouteBuilderStoreActions();
  const routes = useRoutesStore(state => state.routes);
  const settingsStore = useSettings();

  const [isSidebarCollapsed, setIsSidebarCollapsed] = useState(false);
  const [isRouteTooLong, setIsRouteTooLong] = useState(false);
  const [routeNameInput, setRouteNameInput] = useState('');

  // Apply saved default routing profile when opening the builder for a new route
  useEffect(() => {
    if (!editRouteId) {
      const savedProfile =
        settingsStore.app.defaultRoutingProfile ?? 'Car-FastEco';
      setRoutingProfile(savedProfile);
    }
    // Only run on mount / when switching between new-route and edit-route
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [editRouteId]);

  const mapRef = useRef<any>(null);
  const abortControllerRef = useRef<AbortController | null>(null);
  const mapMoveTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const isRouteLoadingFromCacheRef = useRef(false);
  const isRouteDraggingRef = useRef(false);
  const previousRoutePointsCoordsRef = useRef('');
  const previousRoutingProfileRef = useRef('');
  const hydratedEditRouteIdRef = useRef<string | null>(null);
  const pendingInitialEditFetchRouteIdRef = useRef<string | null>(null);
  const pendingInitialEditFetchCoordsRef = useRef('');
  const pendingInitialEditFetchProfileRef = useRef('');

  const [initialViewState] = useState<RouteBuilderMapView>(() =>
    getInitialRouteBuilderView(storedMapView, searchParams)
  );

  useRouteBuilderEffects({
    abortControllerRef,
    editRouteId,
    hydratedEditRouteIdRef,
    isRouteDraggingRef,
    isRouteLoadingFromCacheRef,
    pendingInitialEditFetchCoordsRef,
    pendingInitialEditFetchProfileRef,
    pendingInitialEditFetchRouteIdRef,
    previousRoutePointsCoordsRef,
    previousRoutingProfileRef,
    setIsRouteTooLong,
    setRouteNameInput,
  });

  const actions = useRouteBuilderActions({
    editRouteId,
    isRouteDraggingRef,
    isRouteLoadingFromCacheRef,
    mapMoveTimeoutRef,
    mapRef,
    onRouteGenerated,
    setRouteNameInput,
  });

  const isEditMode = Boolean(editRouteId);
  const originalRoute = useMemo(
    () => routes.find(route => route.id === editRouteId) ?? null,
    [editRouteId, routes]
  );
  const originalRoutePointsCoords = useMemo(() => {
    if (!originalRoute) {
      return '';
    }

    return originalRoute.waypoints
      .map(point => `${point.lat.toFixed(6)},${point.lon.toFixed(6)}`)
      .join('|');
  }, [originalRoute]);
  const currentRoutePointsCoords = useMemo(
    () => buildRoutePointsCoordsString(routePoints),
    [routePoints]
  );
  const hasPendingChanges = Boolean(
    isEditMode &&
    originalRoute &&
    (currentRoutePointsCoords !== originalRoutePointsCoords ||
      routingProfile !== (originalRoute.profile || 'enduro') ||
      routeNameInput.trim() !== (originalRoute.name || '').trim())
  );
  const toggleSidebar = () => setIsSidebarCollapsed(prev => !prev);

  const reloadCurrentRoute = () => {
    if (!editRouteId || !originalRoute) {
      return;
    }

    abortControllerRef.current?.abort();

    const hydratedProfile = originalRoute.profile || 'enduro';
    const hydratedPoints = originalRoute.waypoints.map((point, index) => ({
      id: `edit_point_${originalRoute.id}_${index}`,
      lat: point.lat,
      lon: point.lon,
      color: generateRandomColor(),
      displayName: undefined,
    }));
    const hydratedCoordsString = buildRoutePointsCoordsString(hydratedPoints);

    hydratedEditRouteIdRef.current = editRouteId;
    pendingInitialEditFetchRouteIdRef.current = editRouteId;
    pendingInitialEditFetchCoordsRef.current = hydratedCoordsString;
    pendingInitialEditFetchProfileRef.current = hydratedProfile;
    previousRoutePointsCoordsRef.current = '';
    previousRoutingProfileRef.current = '';
    isRouteLoadingFromCacheRef.current = false;
    isRouteDraggingRef.current = false;

    setError(null);
    setIsRouteLoading(false);
    setIsRouteTooLong(false);
    setGpxUnderlay(null);
    setRouteData(null);
    setTurnPoints(null);
    setLoadingRouteData(null);
    setRoutingProfile(hydratedProfile);
    setRoutePoints(hydratedPoints);
    setSelectedRouteName(originalRoute.name);
    setAutoGeneratedRouteName('');
    setIsRouteNameManuallySet(true);
    setRouteNameInput(originalRoute.name);
  };

  const controller: RouteBuilderControllerValue = {
    autoGeneratedRouteName,
    error,
    gpxUnderlay,
    hasPendingChanges,
    initialViewState,
    isEditMode,
    isRouteLoading,
    isRouteNameManuallySet,
    isRouteTooLong,
    isSidebarCollapsed,
    loadingRouteData,
    mapRef,
    reloadCurrentRoute,
    routeData,
    routeNameInput,
    routePoints,
    routingProfile,
    setIsRouteNameManuallySet,
    setRouteNameInput,
    setRoutingProfile,
    submitLabel: isEditMode
      ? t('routeBuilder:actions.saveChanges')
      : t('routeBuilder:actions.saveRoute'),
    submitLoadingLabel: isEditMode
      ? t('routeBuilder:states.savingChanges')
      : t('routeBuilder:states.savingRoute'),
    toggleSidebar,
    turnPoints,
    ...actions,
  };

  return (
    <RouteBuilderControllerProvider value={controller}>
      <Flex direction="column" height="100%">
        <Flex
          flex={1}
          overflow="hidden"
          direction={{ base: 'column', md: 'row' }}
        >
          <RouteBuilderSidebar />

          <Box flex={1} height="100%" position="relative">
            <Box
              position="absolute"
              top="2px"
              left="50%"
              transform="translateX(-50%)"
              zIndex={20}
              display={{ base: 'block', md: 'none' }}
            >
              <IconButton
                aria-label={
                  isSidebarCollapsed
                    ? t('routeBuilder:actions.showSidebar')
                    : t('routeBuilder:actions.hideSidebar')
                }
                onClick={toggleSidebar}
                size="sm"
                bg={uiColors.toggleButtonBg}
                color={uiColors.toggleButtonColor}
                _hover={{ bg: uiColors.toggleButtonHoverBg }}
                borderRadius="md"
                boxShadow="md"
                transition="all 0.3s ease"
              >
                <span style={{ fontSize: '16px', lineHeight: 1 }}>
                  {isSidebarCollapsed ? '▼' : '▲'}
                </span>
              </IconButton>
            </Box>

            <RouteMap />
          </Box>
        </Flex>
      </Flex>
    </RouteBuilderControllerProvider>
  );
};
